Кручинин К.А., 'Пятнашки', гр. 3530901/00004
Saloed/algorithms-2022-spring pull request #11
Opened 2022-05-22 18:40 UTC by TrombBone

2022-05-26 15:36 UTC, Saloed requested changes

2022-05-26 15:36 UTC, Saloed commented on src/test/kotlin/MyTests.kt
> +    fun randomTest() {
Добавил цикл на 30 итераций. За 10 минут не завершилась даже первая.

2022-05-26 15:36 UTC, Saloed commented on src/test/kotlin/MyTests.kt
> +    fun randomTest() {
Например, `[6, 12, 8, 13, 10, 9, 5, 3, 4, 15, 2, 0, 1, 7, 14, 11]`

2022-05-26 15:36 UTC, Saloed commented on src/main/kotlin/Solver.kt
> +        solve()
Лучше не вызывать такие тяжёлые методы в конструкторе

2022-05-26 15:36 UTC, Saloed commented on src/main/kotlin/Solver.kt
> +    fun solution(): List<Board> = winTrace
Решением всё же является последовательность действий, а не досок

2022-05-26 15:36 UTC, Saloed commented on src/test/kotlin/MyTests.kt
> +    fun randomTest() {
`[11, 9, 12, 14, 0, 10, 7, 13, 2, 5, 8, 4, 15, 1, 3, 6]`

2022-05-26 15:36 UTC, Saloed commented on src/main/kotlin/Board.kt
> +    private fun turn(thisNumbers: Array<IntArray> = numbers, x1: Int, y1: Int, x2: Int, y2: Int): Board? {
Лучше не делать таких параметров по умолчанию

2022-05-26 15:36 UTC, Saloed commented on src/main/kotlin/Board.kt
> +    private fun deepCopy(original: Array<IntArray>): Array<IntArray> {
`Array(original.size) { original[it].copyOf() }`

2022-05-26 15:36 UTC, Saloed commented on src/main/kotlin/Board.kt
> +        for (i in numbers.indices) for (j in numbers[i].indices)
`numbers.contentDeepEquals(other.numbers)`

2022-05-26 15:36 UTC, Saloed commented on src/main/kotlin/Board.kt
> +    override fun hashCode(): Int {
Вроде `numbers` достаточно. Если нет, то в `equals` остальные поля тоже нужно сравнивать

2022-05-27 00:17 UTC, TrombBone commented on src/test/kotlin/MyTests.kt
> +    fun randomTest() {
Исправлено

2022-05-27 00:17 UTC, TrombBone commented on src/main/kotlin/Solver.kt
> +        solve()
Исправлено

2022-05-27 00:17 UTC, TrombBone commented on src/main/kotlin/Solver.kt
> +    fun solution(): List<Board> = winTrace
Исправлено

2022-05-27 00:18 UTC, TrombBone commented on src/main/kotlin/Board.kt
> +    private fun turn(thisNumbers: Array<IntArray> = numbers, x1: Int, y1: Int, x2: Int, y2: Int): Board? {
Исправлено

2022-05-27 00:18 UTC, TrombBone commented on src/main/kotlin/Board.kt
> +    private fun deepCopy(original: Array<IntArray>): Array<IntArray> {
Исправлено. Буду иметь на будущее, очень удобно)

2022-05-27 00:19 UTC, TrombBone commented on src/main/kotlin/Board.kt
> +    override fun hashCode(): Int {
Исправлено. Метод был сгенерирован автоматически, сначала не обратил внимания. Остальные поля действительно не имели значения

2022-05-30 09:25 UTC, closed without merging