Постылякова П.А., 'Решатель для сапера', гр. 3530901/00004
Saloed/algorithms-2022-spring pull request #2
Opened 2022-05-12 20:31 UTC by poletela-na-mars

2022-05-14 16:39 UTC, Saloed requested changes

2022-05-14 16:39 UTC, Saloed commented on src/main/java/game/View.java
> +                if ((boardSize * boardSize <= numOfBombs) || (boardSize > 25) || (boardSize < 2) || (numOfBombs < 1)) {
Ограничение в 25 это как-то очень жёстко. Давайте вообще уберём ограничение сверху

2022-05-14 16:39 UTC, Saloed commented on src/main/java/game/Model.java
> +public class Model {
На доске 100х100 солвер просто зависает. Такого быть не должно

2022-05-15 21:53 UTC, poletela-na-mars commented on src/main/java/game/View.java
> +                if ((boardSize * boardSize <= numOfBombs) || (boardSize > 25) || (boardSize < 2) || (numOfBombs < 1)) {
Исправлено

2022-05-15 21:54 UTC, poletela-na-mars commented on src/main/java/game/Model.java
> +public class Model {
Исправлено. Проблема решена кэшированием картинок и уменьшением их размера

2022-05-19 09:21 UTC, Saloed requested changes
При запуске падает с
```
"JavaFX Application Thread" java.lang.IllegalArgumentException: Image must be non-null
```

2022-05-19 09:21 UTC, Saloed commented on src/main/java/game/Model.java
> +                } else if (group.minesCount == group.cells.size() || group.cells.size() == group.minesCount - group.cells.stream().filter(it -> it.sureBomb).count()) {
Можете пояснить, какой случай покрывает часть условия после `||`?

2022-05-20 11:44 UTC, poletela-na-mars commented on src/main/java/game/Model.java
> +                } else if (group.minesCount == group.cells.size() || group.cells.size() == group.minesCount - group.cells.stream().filter(it -> it.sureBomb).count()) {
Второе условие включается в первое, сейчас его можно убрать. На ранних этапах казалось, что это должно было покрывать отдельные случаи при изменении групп с ячейками

2022-05-20 11:47 UTC, poletela-na-mars commented on src/main/java/game/Model.java
> +                for (int i = 0; i < 100; i++) {
Для более точной коррекции вероятности, чтобы усреднить значение вероятности нахождения для каждой ячейки группы

2022-05-23 11:34 UTC, closed without merging