Багров М.Ю., 'ИИ - русские шашки', гр. 3530901/00004
Saloed/algorithms-2022-spring pull request #3
Opened 2022-05-15 14:29 UTC by TheBigBagrovski

2022-05-18 14:47 UTC, Saloed commented on src/main/code/game/Main.java
> +        InputStream iconStream = getClass().getResourceAsStream("/checkers-icon.png");
Постарайтесь уменьшить дублирование кода

2022-05-18 14:53 UTC, Saloed commented on src/main/code/game/Board.java
> +        public void drawMove(Move move) {
Лучше отделить логику игры от интерфейса

2022-05-19 08:27 UTC, Saloed requested changes

2022-05-19 08:27 UTC, Saloed commented on src/main/code/game/Main.java
> +    public void start(Stage primaryStage) {
То, что написано здесь от того, что написано в `anotherWindow` отличается почти никак.

2022-05-19 08:27 UTC, Saloed commented on src/main/code/game/Board.java
> +        ComputerEnemy firstComputerPlayer;
А переменные вот эти зачем заводить?

2022-05-19 18:46 UTC, TheBigBagrovski commented on src/main/code/game/Board.java
> +        ComputerEnemy firstComputerPlayer;
При инициализации этих переменных начинает работать таймер для ии.

2022-05-22 18:46 UTC, Saloed commented on src/main/code/game/Board.java
> +        ComputerEnemy firstComputerPlayer;
Сами переменные не нужны. Достаточно просто выполнить код, который у них при инициализации выполняется (создать объект)

2022-05-22 19:39 UTC, TheBigBagrovski commented on src/main/code/game/Board.java
> +        ComputerEnemy firstComputerPlayer;
Исправил

2022-05-23 11:24 UTC, closed without merging